remote_theme: fongandrew/hydeout

author:
  name:           'Vivian Nobrega'
  url:            https://shadewyrm.github.io/gc-info-share/


hydeout:
  repo:             https://github.com/ShadeWyrm/gc-info-share
